export const SEND = 'send';
export const EVENT_TYPE = 'event';
export const EVENT_CATEGORY_WORK_CYCLE = 'WORK_CYCLE';
export const EVENT_CATEGORY_SHORT_BREAK_CYCLE = 'BREAK_SHORT_CYCLE';
export const EVENT_CATEGORY_LONG_BREAK_CYCLE = 'BREAK_LONG_CYCLE';
export const EVENT_LABEL_COMPLETE = 'EVENT_LABEL_COMPLETE';
export const EVENT_VALUE_COMPLETE = 1;
