/** SETTINGS **/
export const WORK_DURATION_UPDATE = 'WORK_DURATION_UPDATE';
export const SHORT_BREAK_DURATION_UPDATE = 'SHORT_BREAK_DURATION_UPDATE';
export const LONG_BREAK_DURATION_UPDATE = 'LONG_BREAK_DURATION_UPDATE';
export const RESET_SETTINGS = 'RESET_SETTINGS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

/** TIMER **/
export const STEP_WORK = 'STEP_WORK';
export const STEP_BREAK_SHORT = 'STEP_BREAK_SHORT';
export const STEP_BREAK_LONG = 'STEP_BREAK_LONG';

export const TIMER_DECREASE = 'TIMER_DECREASE';
export const TIMER_RESET = 'TIMER_RESET';
export const TIMER_START = 'TIMER_START';
export const TIMER_STOP = 'TIMER_STOP';
export const TIMER_UPDATE = 'TIMER_UPDATE';
export const STEP_UPDATE = 'STEP_UPDATE';

/** TOMATOROS **/
export const TOMATORO_ADD = 'TOMATORO_ADD';
