import Head from 'next/head'
import React from 'react'

import { Header } from '~/components/organisms/header'
import { TimerWithSelector } from '~/components/templates/timer-with-selector/timer-with-selector.component'

export default function Home () {
  return (
    <>
      <Head>
        <title>Tomatoro</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <Header/>

      <TimerWithSelector/>
    </>
  )
}
