export const SECOND = 1000;

export const TIME = {
    WORK: 60 * 25,
    SHORT_BREAK: 60 * 5,
    LONG_BREAK: 60 * 25,
};

export const emptyFn = () => {
};

/** GA **/
export const SEND = 'SEND';
export const EVENT_TYPE = 'EVENT_TYPE';
export const EVENT_CATEGORY_WORK_CYCLE = 'EVENT_CATEGORY_WORK_CYCLE';
export const EVENT_CATEGORY_SHORT_BREAK_CYCLE = 'EVENT_CATEGORY_SHORT_BREAK_CYCLE';
export const EVENT_CATEGORY_LONG_BREAK_CYCLE = 'EVENT_CATEGORY_LONG_BREAK_CYCLE';
export const EVENT_LABEL_COMPLETE = 'EVENT_LABEL_COMPLETE';
export const EVENT_VALUE_COMPLETE = 'EVENT_VALUE_COMPLETE';
export const GENERIC_CATEGORY = 'GENERIC_CATEGORY';
export const GENERIC_ACTION = 'GENERIC_ACTION';
export const GENERIC_LABEL = 'GENERIC_LABEL';
