/** SETTINGS **/
export const WORK_DURATION_UPDATE = 'WORK_DURATION_UPDATE';
export const SHORT_BREAK_DURATION_UPDATE = 'SHORT_BREAK_DURATION_UPDATE';
export const LONG_BREAK_DURATION_UPDATE = 'LONG_BREAK_DURATION_UPDATE';
export const RESET_SETTINGS = 'RESET_SETTINGS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

/** TIMER **/
export const STEP_WORK = 'STEP_WORK';
export const STEP_BREAK_SHORT = 'STEP_BREAK_SHORT';
export const STEP_BREAK_LONG = 'STEP_BREAK_LONG';

export const TIMER_DECREASE = 'TIMER_DECREASE';
export const TIMER_RESET = 'TIMER_RESET';
export const TIMER_START = 'TIMER_START';
export const TIMER_STOP = 'TIMER_STOP';
export const TIMER_UPDATE = 'TIMER_UPDATE';
export const STEP_UPDATE = 'STEP_UPDATE';

/** TOMATOROS **/
export const TOMATORO_ADD = 'TOMATORO_ADD';

/** GA **/
export const SEND = 'SEND';
export const EVENT_TYPE = 'EVENT_TYPE';
export const EVENT_CATEGORY_WORK_CYCLE = 'EVENT_CATEGORY_WORK_CYCLE';
export const EVENT_CATEGORY_SHORT_BREAK_CYCLE = 'EVENT_CATEGORY_SHORT_BREAK_CYCLE';
export const EVENT_CATEGORY_LONG_BREAK_CYCLE = 'EVENT_CATEGORY_LONG_BREAK_CYCLE';
export const EVENT_LABEL_COMPLETE = 'EVENT_LABEL_COMPLETE';
export const EVENT_VALUE_COMPLETE = 'EVENT_VALUE_COMPLETE';
export const GENERIC_CATEGORY = 'GENERIC_CATEGORY';
export const GENERIC_ACTION = 'GENERIC_ACTION';
export const GENERIC_LABEL = 'GENERIC_LABEL';

